name = "qahal-dev"
main = "src/index.ts"
compatibility_date = "2026-04-19"
workers_dev = true
preview_urls = true

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "qahal-db-test"
database_id = "81652040-b23b-4841-bd48-a129b3d34d5a"
migrations_dir = "migrations"

[vars]
# Comma-separated list, for example:
# CORS_ALLOWED_ORIGINS = "https://development.qahal.xyz,https://app.qahal.xyz"
CORS_ALLOWED_ORIGINS = "https://development.qahal.xyz,https://app.qahal.xyz"
APP_ENV = "development"

[[routes]]
pattern = "api-development.qahal.xyz"
zone_name = "qahal.xyz"
custom_domain = true

[env.production.vars]
APP_ENV = "production"
CORS_ALLOWED_ORIGINS = "https://development.qahal.xyz,https://app.qahal.xyz"

[env.production]
name = "qahal"
workers_dev = true
preview_urls = true

[[env.production.routes]]
pattern = "api.qahal.xyz"
zone_name = "qahal.xyz"
custom_domain = true

[[env.production.d1_databases]]
binding = "DB"
database_name = "qahal-db-prod"
database_id = "bc3c7a13-6714-4396-af65-728eda27aa7c"
migrations_dir = "migrations"
