INSERT OR IGNORE INTO community_people (id, community_id, name, city, country, location_key) VALUES
  (103, 2, 'Hannah bat Eli', 'Buenos Aires', 'Argentina', 'buenos-aires'),
  (104, 3, 'Elijah ben Tishbi', 'Buenos Aires', 'Argentina', 'buenos-aires'),
  (203, 5, 'Isaac ben Abraham', 'Mar de Ajo', 'Argentina', 'mar-de-ajo'),
  (204, 6, 'Leah bat Laban', 'Mar de Ajo', 'Argentina', 'mar-de-ajo'),
  (303, 8, 'Martha', 'Lima', 'Peru', 'lima'),
  (304, 9, 'Lydia', 'Lima', 'Peru', 'lima'),
  (403, 11, 'Rachel', 'Madrid', 'Spain', 'madrid'),
  (404, 12, 'Naomi', 'Madrid', 'Spain', 'madrid'),
  (503, 14, 'Zipporah', 'Ciudad de Mexico', 'Mexico', 'ciudad-de-mexico'),
  (504, 15, 'Asher', 'Ciudad de Mexico', 'Mexico', 'ciudad-de-mexico'),
  (603, 17, 'Micah', 'Jacksonville', 'USA', 'jacksonville'),
  (604, 18, 'Priscilla', 'Jacksonville', 'USA', 'jacksonville');

INSERT OR IGNORE INTO community_person_badges (person_id, kind, label, years) VALUES
  (103, 'emunah', 'Emunah', NULL),
  (103, 'hebrew-teacher', 'Hebrew Teacher', NULL),
  (104, 'kehilah', 'Kehilah', NULL),
  (104, 'years', 'Years in Emunah', 3),
  (203, 'emunah', 'Emunah', NULL),
  (203, 'hebrew-student', 'Hebrew Student', NULL),
  (204, 'kehilah', 'Kehilah', NULL),
  (204, 'messenger', 'Messenger', NULL),
  (303, 'emunah', 'Emunah', NULL),
  (303, 'hebrew-student', 'Hebrew Student', NULL),
  (304, 'kehilah', 'Kehilah', NULL),
  (304, 'hebrew-teacher', 'Hebrew Teacher', NULL),
  (403, 'emunah', 'Emunah', NULL),
  (403, 'hebrew-student', 'Hebrew Student', NULL),
  (404, 'kehilah', 'Kehilah', NULL),
  (404, 'years', 'Years in Emunah', 2),
  (503, 'emunah', 'Emunah', NULL),
  (503, 'messenger', 'Messenger', NULL),
  (504, 'kehilah', 'Kehilah', NULL),
  (504, 'hebrew-teacher', 'Hebrew Teacher', NULL),
  (603, 'emunah', 'Emunah', NULL),
  (603, 'years', 'Years in Emunah', 4),
  (604, 'kehilah', 'Kehilah', NULL),
  (604, 'hebrew-student', 'Hebrew Student', NULL);
